name: Jonathan Egholm
favicon: null
layout_spectrum: 0.96861
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4295c1'
    - '#254f65'
    - '#e7e7e7'
    - '#787f78'
    - '#c8b5ae'
  brandStrength: 0.6875
  lightness: 0.4769247022923082
  saturation: 0.9346141102723777
  rhythmicContrast: 0.5
purpose: []
